Check args in the deprecate model flow
iterative/gto pull request #427
Opened 2023-10-12 12:17 UTC by tapadipti

`check_args()` also validates the model name. Earlier, the model name was not being validated for the deprecate model action. It was getting validated for all other actions including the unassign and deregister actions (which are variations of the deprecate action).

2023-10-12 23:20 UTC, shcheklein commented
Thanks @tapadipti ! I left a comment + I think we would need a test for this.

2023-10-13 07:04 UTC, tapadipti commented on gto/registry.py
> +        self._check_args(name=name, version=None, rev=rev, deprecate_model=True)
[Done](https://github.com/iterative/gto/pull/427/commits/1ddc807b6aeb5c558c9bea019bff7d60acc79fb2)

2023-10-13 07:08 UTC, tapadipti commented
Thanks @shcheklein. I've addressed your comments.

For the test, I ran it locally by calling it from a `__main__` block. But I'm not sure how to run it without that.

There are more validations to be added. Eg, currently it accepts `//` in the name, and this is not allowed in the Git ref. I'll work on fixing this as part of https://github.com/iterative/dvc/issues/9821 but it's not within the scope of this PR.

2023-10-13 21:47 UTC, shcheklein approved these changes

2023-10-13 21:48 UTC, shcheklein commented
thanks @tapadipti ! it looks good, but it seems we need to fix the test. Please see the checks above.

2023-10-16 05:05 UTC, tapadipti commented
> it seems we need to fix the test. Please see the checks above.

The error message returned by the name validation functions is quite long. So it looks like a new line character (`\n`) gets added automatically - see the extra `\n` between `Value ` and `must` below:

`❌ Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value \nmust be of len >= 2 and must start and end with a letter or a number.\n`

Is there a way to turn off this automatic addition?

I was not adding this `\n` to my test (coz I wasn't expecting it to get added when running), and locally I didn't see this issue.

To resolve this, I've now added the `\n` to the error message and to my test. It's passing now.

However, I'm not sure if some other products with dependencies on GTO could break due to this (if they're expecting a string without this `\n`). cc @iterative/studio

2023-10-16 06:01 UTC, amritghimire approved these changes

2023-10-17 06:21 UTC, tapadipti commented
> @tapadipti I think it's better to not alter the behavior, but rather fix test to be more lax on comparison. E.g. remove all `\n` before comparing the result.

@shcheklein I've done this [here](https://github.com/iterative/gto/pull/427/commits/0834b164e1233788eb739ef83ab240ba3247bcea#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR21). All tests passed, so it should be fine.

2023-10-17 09:44 UTC, tapadipti commented
@shcheklein I’ve tried 2 ways to remove the `\n`. But it’s not working, coz it seems the `\n` is being escaped and so the character is `\\n`. This does not happen locally, so I don’t know how to resolve this. I even tried substituting `\\n` - as I expected, that does not help either (I've removed that commit). This is the error which needs to be cleaned of the line breaks:

`"\u274c Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value\\nmust be of len >= 2 and must start and end with a letter or a number.\\n"`

2023-10-17 16:20 UTC, shcheklein commented
@tapadipti do you have sense on why is it escaped? what other symbols are escaped?

2023-10-18 06:31 UTC, tapadipti commented
> @tapadipti do you have sense on why is it escaped? what other symbols are escaped?

@shcheklein No, I couldn't figure this out - for some reason the `\` in `\n` is being escaped, so it becomes `\\n`. When I try locally, a string with `\\n` prints just `\n`. And I don't know how to replicate how the complete test suite is being run - I've run individual tests and it works fine. The only character causing me issue is the line break which is getting added in the middle of a line. Without this extra line break, there's no issue coz all the other line breaks are at the same position in both the actual and expected values.

2023-10-18 07:42 UTC, pmrowla requested changes
The GTO CLI test framework is fragile (and IMO a lot of these tests are not actually useful either) since all of the tests are hard coded to check for fixed output. 

The issue that shows up here is that the underlying test for CLI commands uses `click.CliRunner` which will implements line wrapping at a fixed maximum content width of 80. Wrapped lines will also be split using the platform specific line ending (which is CRLF on windows and not just LF). This was a non-issue for all of the other existing tests up to now (purely by coincidence) since none of them generate a line longer than 80 characters.

Adjusting the test framework to strip all newlines and replace them with spaces is probably not the right way to go since the newlines are explicitly expected output in all of the other existing tests.

The fix here should be to just manually handle the line wrapping at 80 characters in the new test like
```python
def test_deprecate_artifact(repo_with_commit: str):
    expected = os.linesep.join(
        [
            (
                "❌ Invalid value 'a4!'."
                " Only letters, numbers, '_', '-', '/' are allowed. Value "
            ),
            (
                "must be of len >= 2 and must start and end with a letter or"
                " a number.\n"
            ),
        ]
    )
    _check_failing_cmd(
        "deprecate",
        ["-r", repo_with_commit, "a4!"],
        expected,
    )
```

(this should fix the test failures and should not require modifying `_check_output_exact_match` at all in this PR)

2023-10-18 07:46 UTC, pmrowla commented
ideally in the long term all of the tests should be updated to work off of a list of expected lines instead of a single hard coded string, and then the check functions would do something like
```
assert result.stdout.splitlines() == expected_stdout
assert result.stderr.splitlines() == expected_stderr
```
which will work regardless of platform/line ending, and it will account for commands where the newlines in output are significant

2023-10-18 08:01 UTC, tapadipti commented
@pmrowla Yes. 

> Wrapped lines will also be split using the platform specific line ending (which is CRLF on windows and not just LF)

I wish this comment was here yesterday or earlier today. Figured it out the hard way today. Have fixed it by doing replace differently for Windows. Which I don't like. So I'll revert to what you've suggested - which is pretty much what I had [here](https://github.com/iterative/gto/pull/427/commits/673a657eb87a1e44265c05e857eb1af850e847b3) and [here](https://github.com/iterative/gto/pull/427/commits/3fb76767cd2bbf3ea9b9179f9a22dda422c8d3ee). @shcheklein Can you pls confirm you're ok with this - coz you'd earlier suggested `I think it's better to not alter the behavior, but rather fix test to be more lax on comparison. E.g. remove all \n before comparing the result.`

2023-10-18 08:09 UTC, pmrowla commented
> I think it's better to not alter the behavior, but rather fix test to be more lax on comparison. E.g. remove all \n before comparing the result.

The problem with this is that this is applied to the tests for every GTO command and it strips the line breaks in places where the test behavior is actually significant, i.e. when the expected output is explicitly
```
To push the changes upstream, run:
    git push origin nn2@v0.0.1
```

Stripping/replacing all the line breaks means the test would now pass if the CLI command outputs
```
To push the changes upstream, run:     git push origin nn2@v0.0.1
```

2023-10-19 07:11 UTC, tapadipti commented
@pmrowla I tried removing the manual line breaks in the exception message, as you suggested. But it's not working - it looks like the space between `Value ` and `must` is getting stripped in Windows. See the assertion errors in the test reports for the latest commits.

<details>
<summary>
Summary of error: 
</summary>

When I use [your suggested code](https://github.com/iterative/gto/pull/427#pullrequestreview-1684318123) for the test (in [this commit](https://github.com/iterative/gto/pull/427/commits/ab1b866ecefd99fbf3b949c9bfe73fdce8792c67)), I get the following mismatch between the actual and expected values.

`
"\u274c Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value\\nmust be of len >= 2 and must start and end with a letter or a number.\\n"
`
`
"\u274c Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value \\r\\nmust be of len >= 2 and must start and end with a letter or a number.\\n"
`

If I use a `\n` in the test (see [this commit](https://github.com/iterative/gto/pull/427/commits/371e120defae679d90ab7f08b2d3bbdce4f6311f#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR357)), I get the following mismatch:

`
"\u274c Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value\\nmust be of len >= 2 and must start and end with a letter or a number.\\n"
`
`
"\u274c Invalid value 'a4!'. Only letters, numbers, '_', '-', '/' are allowed. Value \\nmust be of len >= 2 and must start and end with a letter or a number.\\n"
`
</details>


From what I saw yesterday, this (stripping) does not happen in ubuntu and macos, so I can't just remove the space from the expected value (else the test will fail in ubuntu and macos). I can treat Windows differently (similar to how I did [here](https://github.com/iterative/gto/pull/427/commits/7196ef8eb97813c580c7dd98927daf9330ba815c#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR28)), but imo that's a terrible idea. So my only option now is to revert to adding the manual line break in the exception message (or to improve how the tests are written, which I don't want to make part/dependency of this PR).

2023-10-19 12:40 UTC, dberenbaum commented
Hope this helps and isn't further derailing here, but can you strip only the `\r` clrf windows-style line endings from the actual output? I don't think we are ever going to intentionally add those into output.

2023-10-19 12:57 UTC, pmrowla commented
We should just remove this CLI test entirely and test the underlying behavior in `test_api` instead like
```python
with pytest.raises(ValidationError):
    api.deregister(...)  # call deregister with an invalid name
```

2023-10-20 05:53 UTC, tapadipti commented
For now, I'm removing the test. I've created [an issue to improve tests](https://github.com/iterative/gto/issues/429), and we can add a test for the deprecate model action with invalid model name there. cc @pmrowla @shcheklein @dberenbaum

2023-10-25 14:46 UTC, tapadipti commented
@pmrowla Can you ptal at [this comment](https://github.com/iterative/gto/pull/427#issuecomment-1772125376) and re-review this PR. I can't merge the PR without you accepting the change.

2023-10-26 00:13 UTC, pmrowla approved these changes

2023-10-26 02:37 UTC, merged